/**
 * A curated set of well-known airports for the guessing game.
 *
 * Source: OurAirports open data (public domain), filtered to airports with
 * scheduled service that a 12-year-old has a fair chance of placing on a map.
 * `tier: 1` marks the household names, used for the opening round so the game
 * does not start with somewhere nobody has heard of.
 */

export interface GameAirport {
  iata: string;
  icao: string;
  name: string;
  city: string;
  /** ISO 3166-1 alpha-2. */
  country: string;
  lat: number;
  lon: number;
  tier: 1 | 2;
}

export const AIRPORTS: GameAirport[] = [
  { iata: 'ADD', icao: 'HAAB', name: 'Addis Ababa Bole International Airport', city: 'Addis Ababa', country: 'ET', lat: 8.9779, lon: 38.7993, tier: 1 },
  { iata: 'AKL', icao: 'NZAA', name: 'Auckland International Airport', city: 'Auckland', country: 'NZ', lat: -37.012, lon: 174.7863, tier: 1 },
  { iata: 'AMS', icao: 'EHAM', name: 'Amsterdam Airport Schiphol', city: 'Amsterdam', country: 'NL', lat: 52.3086, lon: 4.7639, tier: 1 },
  { iata: 'ARN', icao: 'ESSA', name: 'Stockholm-Arlanda Airport', city: 'Stockholm', country: 'SE', lat: 59.6485, lon: 17.9288, tier: 1 },
  { iata: 'ATH', icao: 'LGAV', name: 'Athens Eleftherios Venizelos International Airport', city: 'Spata-Artemida', country: 'GR', lat: 37.9364, lon: 23.9445, tier: 1 },
  { iata: 'ATL', icao: 'KATL', name: 'Hartsfield Jackson Atlanta International Airport', city: 'Atlanta', country: 'US', lat: 33.6367, lon: -84.4281, tier: 1 },
  { iata: 'AUH', icao: 'OMAA', name: 'Zayed International Airport', city: 'Abu Dhabi', country: 'AE', lat: 24.441, lon: 54.6492, tier: 1 },
  { iata: 'AYT', icao: 'LTAI', name: 'Antalya International Airport', city: 'Antalya', country: 'TR', lat: 36.8987, lon: 30.8005, tier: 2 },
  { iata: 'BAH', icao: 'OBBI', name: 'Bahrain International Airport', city: 'Manama', country: 'BH', lat: 26.2673, lon: 50.6376, tier: 2 },
  { iata: 'BCN', icao: 'LEBL', name: 'Josep Tarradellas Barcelona-El Prat Airport', city: 'Barcelona', country: 'ES', lat: 41.2971, lon: 2.0785, tier: 1 },
  { iata: 'BER', icao: 'EDDB', name: 'Berlin Brandenburg Airport', city: 'Berlin', country: 'DE', lat: 52.3617, lon: 13.5023, tier: 1 },
  { iata: 'BKK', icao: 'VTBS', name: 'Suvarnabhumi Airport', city: 'Bangkok', country: 'TH', lat: 13.6811, lon: 100.747, tier: 1 },
  { iata: 'BLR', icao: 'VOBL', name: 'Kempegowda International Airport Bengaluru', city: 'Bengaluru', country: 'IN', lat: 13.1979, lon: 77.7063, tier: 2 },
  { iata: 'BNE', icao: 'YBBN', name: 'Brisbane International Airport', city: 'Brisbane', country: 'AU', lat: -27.3842, lon: 153.117, tier: 2 },
  { iata: 'BOG', icao: 'SKBO', name: 'El Dorado International Airport', city: 'Bogota', country: 'CO', lat: 4.7016, lon: -74.1469, tier: 1 },
  { iata: 'BOM', icao: 'VABB', name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai', country: 'IN', lat: 19.0887, lon: 72.8679, tier: 1 },
  { iata: 'BOS', icao: 'KBOS', name: 'Boston Logan International Airport', city: 'Boston', country: 'US', lat: 42.362, lon: -71.0079, tier: 1 },
  { iata: 'BRU', icao: 'EBBR', name: 'Brussels Airport', city: 'Zaventem', country: 'BE', lat: 50.9014, lon: 4.4844, tier: 2 },
  { iata: 'BUD', icao: 'LHBP', name: 'Budapest Liszt Ferenc International Airport', city: 'Budapest', country: 'HU', lat: 47.4302, lon: 19.2624, tier: 2 },
  { iata: 'CAI', icao: 'HECA', name: 'Cairo International Airport', city: 'Cairo', country: 'EG', lat: 30.1115, lon: 31.3967, tier: 1 },
  { iata: 'CAN', icao: 'ZGGG', name: 'Guangzhou Baiyun International Airport', city: 'Guangzhou (Huadu)', country: 'CN', lat: 23.3924, lon: 113.299, tier: 1 },
  { iata: 'CCU', icao: 'VECC', name: 'Netaji Subhash Chandra Bose International Airport', city: 'Kolkata', country: 'IN', lat: 22.654, lon: 88.4476, tier: 2 },
  { iata: 'CDG', icao: 'LFPG', name: 'Charles de Gaulle International Airport', city: 'Paris (Roissy-en-France, Val-d\'Oise)', country: 'FR', lat: 49.009, lon: 2.5541, tier: 1 },
  { iata: 'CEB', icao: 'RPVM', name: 'Mactan Cebu International Airport', city: 'Cebu City/Lapu-Lapu City', country: 'PH', lat: 10.3093, lon: 123.9797, tier: 2 },
  { iata: 'CGK', icao: 'WIII', name: 'Soekarno-Hatta International Airport', city: 'Jakarta', country: 'ID', lat: -6.1256, lon: 106.656, tier: 1 },
  { iata: 'CHC', icao: 'NZCH', name: 'Christchurch International Airport', city: 'Christchurch', country: 'NZ', lat: -43.489, lon: 172.5321, tier: 2 },
  { iata: 'CJU', icao: 'RKPC', name: 'Jeju International Airport', city: 'Jeju City', country: 'KR', lat: 33.5121, lon: 126.4925, tier: 1 },
  { iata: 'CMB', icao: 'VCBI', name: 'Bandaranaike International Colombo Airport', city: 'Colombo', country: 'LK', lat: 7.1808, lon: 79.8841, tier: 2 },
  { iata: 'CMN', icao: 'GMMN', name: 'Mohammed V International Airport', city: 'Casablanca', country: 'MA', lat: 33.3675, lon: -7.59, tier: 1 },
  { iata: 'CPH', icao: 'EKCH', name: 'Copenhagen Kastrup Airport', city: 'Copenhagen', country: 'DK', lat: 55.6179, lon: 12.656, tier: 1 },
  { iata: 'CPT', icao: 'FACT', name: 'Cape Town International Airport', city: 'Cape Town', country: 'ZA', lat: -33.974, lon: 18.6043, tier: 1 },
  { iata: 'CTS', icao: 'RJCC', name: 'New Chitose Airport', city: 'Sapporo', country: 'JP', lat: 42.7748, lon: 141.6904, tier: 2 },
  { iata: 'CTU', icao: 'ZUUU', name: 'Chengdu Shuangliu International Airport', city: 'Chengdu (Shuangliu)', country: 'CN', lat: 30.5583, lon: 103.946, tier: 2 },
  { iata: 'CUN', icao: 'MMUN', name: 'Cancún International Airport', city: 'Cancún', country: 'MX', lat: 21.0408, lon: -86.8735, tier: 1 },
  { iata: 'DAC', icao: 'VGHS', name: 'Hazrat Shahjalal International Airport', city: 'Dhaka', country: 'BD', lat: 23.8433, lon: 90.3978, tier: 2 },
  { iata: 'DAD', icao: 'VVDN', name: 'Da Nang International Airport', city: 'Da Nang', country: 'VN', lat: 16.0439, lon: 108.199, tier: 2 },
  { iata: 'DCA', icao: 'KDCA', name: 'Ronald Reagan Washington National Airport', city: 'Washington', country: 'US', lat: 38.8521, lon: -77.0377, tier: 2 },
  { iata: 'DEL', icao: 'VIDP', name: 'Indira Gandhi International Airport', city: 'New Delhi', country: 'IN', lat: 28.5556, lon: 77.0952, tier: 1 },
  { iata: 'DEN', icao: 'KDEN', name: 'Denver International Airport', city: 'Denver', country: 'US', lat: 39.86, lon: -104.6738, tier: 1 },
  { iata: 'DFW', icao: 'KDFW', name: 'Dallas Fort Worth International Airport', city: 'Dallas-Fort Worth', country: 'US', lat: 32.8968, lon: -97.038, tier: 1 },
  { iata: 'DMK', icao: 'VTBD', name: 'Don Mueang International Airport', city: 'Bangkok', country: 'TH', lat: 13.9126, lon: 100.607, tier: 2 },
  { iata: 'DOH', icao: 'OTHH', name: 'Hamad International Airport', city: 'Doha', country: 'QA', lat: 25.2731, lon: 51.6081, tier: 1 },
  { iata: 'DPS', icao: 'WADD', name: 'Denpasar I Gusti Ngurah Rai International Airport', city: 'Kuta, Badung', country: 'ID', lat: -8.7484, lon: 115.1671, tier: 1 },
  { iata: 'DUB', icao: 'EIDW', name: 'Dublin Airport', city: 'Dublin', country: 'IE', lat: 53.4287, lon: -6.2621, tier: 1 },
  { iata: 'DUS', icao: 'EDDL', name: 'Düsseldorf Airport', city: 'Düsseldorf', country: 'DE', lat: 51.2895, lon: 6.7668, tier: 2 },
  { iata: 'DXB', icao: 'OMDB', name: 'Dubai International Airport', city: 'Dubai', country: 'AE', lat: 25.2498, lon: 55.371, tier: 1 },
  { iata: 'EDI', icao: 'EGPH', name: 'Edinburgh Airport', city: 'Ingliston, Edinburgh', country: 'GB', lat: 55.9501, lon: -3.3723, tier: 2 },
  { iata: 'EWR', icao: 'KEWR', name: 'Newark Liberty International Airport', city: 'Newark', country: 'US', lat: 40.6894, lon: -74.1705, tier: 2 },
  { iata: 'EZE', icao: 'SAEZ', name: 'Ezeiza International Airport - Ministro Pistarini', city: 'Buenos Aires (Ezeiza)', country: 'AR', lat: -34.8222, lon: -58.5358, tier: 1 },
  { iata: 'FCO', icao: 'LIRF', name: 'Rome–Fiumicino Leonardo da Vinci International Airport', city: 'Rome', country: 'IT', lat: 41.8045, lon: 12.252, tier: 1 },
  { iata: 'FRA', icao: 'EDDF', name: 'Frankfurt Main Airport', city: 'Frankfurt am Main', country: 'DE', lat: 50.0267, lon: 8.5584, tier: 1 },
  { iata: 'FUK', icao: 'RJFF', name: 'Fukuoka Airport', city: 'Fukuoka', country: 'JP', lat: 33.5859, lon: 130.451, tier: 2 },
  { iata: 'GIG', icao: 'SBGL', name: 'Rio Galeão – Tom Jobim International Airport', city: 'Rio De Janeiro', country: 'BR', lat: -22.81, lon: -43.2506, tier: 2 },
  { iata: 'GMP', icao: 'RKSS', name: 'Seoul Gimpo International Airport', city: 'Seoul', country: 'KR', lat: 37.5583, lon: 126.791, tier: 1 },
  { iata: 'GRU', icao: 'SBGR', name: 'São Paulo/Guarulhos–Governor André Franco Montoro International Airport', city: 'São Paulo', country: 'BR', lat: -23.4313, lon: -46.47, tier: 1 },
  { iata: 'GUM', icao: 'PGUM', name: 'Antonio B. Won Pat International Airport', city: 'Hagåtña', country: 'GU', lat: 13.485, lon: 144.7973, tier: 1 },
  { iata: 'GVA', icao: 'LSGG', name: 'Geneva International Airport', city: 'Geneva', country: 'CH', lat: 46.2381, lon: 6.109, tier: 2 },
  { iata: 'HAM', icao: 'EDDH', name: 'Hamburg Helmut Schmidt Airport', city: 'Hamburg', country: 'DE', lat: 53.6304, lon: 9.9882, tier: 2 },
  { iata: 'HAN', icao: 'VVNB', name: 'Noi Bai International Airport', city: 'Hanoi (Soc Son)', country: 'VN', lat: 21.2212, lon: 105.807, tier: 1 },
  { iata: 'HEL', icao: 'EFHK', name: 'Helsinki Vantaa Airport', city: 'Helsinki (Vantaa)', country: 'FI', lat: 60.3184, lon: 24.9633, tier: 2 },
  { iata: 'HKG', icao: 'VHHH', name: 'Hong Kong International Airport', city: 'Hong Kong', country: 'HK', lat: 22.3118, lon: 113.9149, tier: 1 },
  { iata: 'HKT', icao: 'VTSP', name: 'Phuket International Airport', city: 'Phuket', country: 'TH', lat: 8.1133, lon: 98.3174, tier: 2 },
  { iata: 'HND', icao: 'RJTT', name: 'Tokyo Haneda International Airport', city: 'Tokyo', country: 'JP', lat: 35.5497, lon: 139.787, tier: 1 },
  { iata: 'HNL', icao: 'PHNL', name: 'Daniel K. Inouye International Airport', city: 'Honolulu, Oahu', country: 'US', lat: 21.3184, lon: -157.9257, tier: 1 },
  { iata: 'HYD', icao: 'VOHS', name: 'Rajiv Gandhi International Airport', city: 'Hyderabad', country: 'IN', lat: 17.2313, lon: 78.4299, tier: 2 },
  { iata: 'IAD', icao: 'KIAD', name: 'Washington Dulles International Airport', city: 'Dulles', country: 'US', lat: 38.9445, lon: -77.4558, tier: 2 },
  { iata: 'IAH', icao: 'KIAH', name: 'George Bush Intercontinental Airport', city: 'Houston', country: 'US', lat: 29.9844, lon: -95.3414, tier: 2 },
  { iata: 'ICN', icao: 'RKSI', name: 'Incheon International Airport', city: 'Seoul', country: 'KR', lat: 37.4691, lon: 126.451, tier: 1 },
  { iata: 'IST', icao: 'LTFM', name: 'İstanbul Airport', city: 'Istanbul', country: 'TR', lat: 41.2749, lon: 28.7321, tier: 1 },
  { iata: 'ITM', icao: 'RJOO', name: 'Osaka Itami International Airport', city: 'Osaka', country: 'JP', lat: 34.7809, lon: 135.4408, tier: 2 },
  { iata: 'JED', icao: 'OEJN', name: 'King Abdulaziz International Airport', city: 'Jeddah', country: 'SA', lat: 21.6802, lon: 39.1574, tier: 2 },
  { iata: 'JFK', icao: 'KJFK', name: 'John F. Kennedy International Airport', city: 'New York', country: 'US', lat: 40.6394, lon: -73.7793, tier: 1 },
  { iata: 'JNB', icao: 'FAOR', name: 'O.R. Tambo International Airport', city: 'Johannesburg', country: 'ZA', lat: -26.1401, lon: 28.2468, tier: 1 },
  { iata: 'KEF', icao: 'BIKF', name: 'Keflavik International Airport', city: 'Reykjavík', country: 'IS', lat: 63.985, lon: -22.6056, tier: 2 },
  { iata: 'KIX', icao: 'RJBB', name: 'Kansai International Airport', city: 'Osaka', country: 'JP', lat: 34.4273, lon: 135.244, tier: 1 },
  { iata: 'KTM', icao: 'VNKT', name: 'Tribhuvan International Airport', city: 'Kathmandu', country: 'NP', lat: 27.6966, lon: 85.3591, tier: 2 },
  { iata: 'KUL', icao: 'WMKK', name: 'Kuala Lumpur International Airport', city: 'Sepang', country: 'MY', lat: 2.7456, lon: 101.71, tier: 1 },
  { iata: 'KWI', icao: 'OKKK', name: 'Kuwait International Airport', city: 'Kuwait City', country: 'KW', lat: 29.2245, lon: 47.9698, tier: 2 },
  { iata: 'LAS', icao: 'KLAS', name: 'Harry Reid International Airport', city: 'Las Vegas', country: 'US', lat: 36.0834, lon: -115.1518, tier: 1 },
  { iata: 'LAX', icao: 'KLAX', name: 'Los Angeles International Airport', city: 'Los Angeles', country: 'US', lat: 33.9425, lon: -118.408, tier: 1 },
  { iata: 'LED', icao: 'ULLI', name: 'Pulkovo Airport', city: 'St. Petersburg', country: 'RU', lat: 59.8003, lon: 30.2625, tier: 2 },
  { iata: 'LGA', icao: 'KLGA', name: 'LaGuardia Airport', city: 'New York', country: 'US', lat: 40.7772, lon: -73.8726, tier: 2 },
  { iata: 'LGW', icao: 'EGKK', name: 'London Gatwick Airport', city: 'London', country: 'GB', lat: 51.1487, lon: -0.1857, tier: 2 },
  { iata: 'LHR', icao: 'EGLL', name: 'London Heathrow Airport', city: 'London', country: 'GB', lat: 51.4707, lon: -0.4599, tier: 1 },
  { iata: 'LIM', icao: 'SPJC', name: 'Jorge Chávez International Airport', city: 'Lima', country: 'PE', lat: -12.0219, lon: -77.1143, tier: 1 },
  { iata: 'LIS', icao: 'LPPT', name: 'Lisbon Humberto Delgado Airport', city: 'Lisbon', country: 'PT', lat: 38.7813, lon: -9.1359, tier: 1 },
  { iata: 'LOS', icao: 'DNMM', name: 'Murtala Muhammed International Airport', city: 'Lagos', country: 'NG', lat: 6.5774, lon: 3.3212, tier: 2 },
  { iata: 'MAA', icao: 'VOMM', name: 'Chennai International Airport', city: 'Chennai', country: 'IN', lat: 12.99, lon: 80.1693, tier: 2 },
  { iata: 'MAD', icao: 'LEMD', name: 'Adolfo Suárez Madrid–Barajas Airport', city: 'Madrid', country: 'ES', lat: 40.4934, lon: -3.5722, tier: 1 },
  { iata: 'MAN', icao: 'EGCC', name: 'Manchester Airport', city: 'Manchester, Greater Manchester', country: 'GB', lat: 53.3494, lon: -2.2795, tier: 2 },
  { iata: 'MCO', icao: 'KMCO', name: 'Orlando International Airport', city: 'Orlando', country: 'US', lat: 28.4294, lon: -81.309, tier: 2 },
  { iata: 'MCT', icao: 'OOMS', name: 'Muscat International Airport', city: 'Muscat/Seeb', country: 'OM', lat: 23.6002, lon: 58.2853, tier: 2 },
  { iata: 'MEL', icao: 'YMML', name: 'Melbourne Airport', city: 'Melbourne', country: 'AU', lat: -37.6707, lon: 144.8379, tier: 1 },
  { iata: 'MEX', icao: 'MMMX', name: 'Mexico City Benito Juárez International Airport', city: 'Mexico City', country: 'MX', lat: 19.4358, lon: -99.0703, tier: 1 },
  { iata: 'MFM', icao: 'VMMC', name: 'Macau International Airport', city: 'Nossa Senhora do Carmo', country: 'MO', lat: 22.1496, lon: 113.592, tier: 2 },
  { iata: 'MIA', icao: 'KMIA', name: 'Miami International Airport', city: 'Miami', country: 'US', lat: 25.796, lon: -80.2898, tier: 1 },
  { iata: 'MLE', icao: 'VRMM', name: 'Velana International Airport', city: 'Malé', country: 'MV', lat: 4.1918, lon: 73.5291, tier: 2 },
  { iata: 'MNL', icao: 'RPLL', name: 'Ninoy Aquino International Airport', city: 'Manila (Pasay)', country: 'PH', lat: 14.5086, lon: 121.02, tier: 1 },
  { iata: 'MUC', icao: 'EDDM', name: 'Munich Airport', city: 'Munich', country: 'DE', lat: 48.3538, lon: 11.7861, tier: 1 },
  { iata: 'MXP', icao: 'LIMC', name: 'Milan Malpensa International Airport', city: 'Ferno (VA)', country: 'IT', lat: 45.6306, lon: 8.7281, tier: 2 },
  { iata: 'NAN', icao: 'NFFN', name: 'Nadi International Airport', city: 'Nadi', country: 'FJ', lat: -17.7618, lon: 177.4378, tier: 2 },
  { iata: 'NBO', icao: 'HKJK', name: 'Jomo Kenyatta International Airport', city: 'Nairobi', country: 'KE', lat: -1.3189, lon: 36.9282, tier: 1 },
  { iata: 'NCE', icao: 'LFMN', name: 'Nice-Côte d\'Azur Airport', city: 'Nice, Alpes-Maritimes', country: 'FR', lat: 43.6584, lon: 7.2159, tier: 2 },
  { iata: 'NRT', icao: 'RJAA', name: 'Narita International Airport', city: 'Narita', country: 'JP', lat: 35.7686, lon: 140.3887, tier: 1 },
  { iata: 'OKA', icao: 'ROAH', name: 'Naha International Airport', city: 'Naha', country: 'JP', lat: 26.1924, lon: 127.6398, tier: 2 },
  { iata: 'OPO', icao: 'LPPR', name: 'Francisco de Sá Carneiro Airport', city: 'Porto', country: 'PT', lat: 41.2481, lon: -8.6814, tier: 2 },
  { iata: 'ORD', icao: 'KORD', name: 'Chicago O\'Hare International Airport', city: 'Chicago', country: 'US', lat: 41.9786, lon: -87.9048, tier: 1 },
  { iata: 'ORY', icao: 'LFPO', name: 'Paris-Orly Airport', city: 'Paris (Orly, Val-de-Marne)', country: 'FR', lat: 48.7295, lon: 2.359, tier: 2 },
  { iata: 'OSL', icao: 'ENGM', name: 'Oslo-Gardermoen International Airport', city: 'Oslo (Gardermoen)', country: 'NO', lat: 60.1939, lon: 11.1004, tier: 2 },
  { iata: 'PEK', icao: 'ZBAA', name: 'Beijing Capital International Airport', city: 'Beijing', country: 'CN', lat: 40.0773, lon: 116.5967, tier: 1 },
  { iata: 'PER', icao: 'YPPH', name: 'Perth International Airport', city: 'Perth', country: 'AU', lat: -31.9403, lon: 115.967, tier: 2 },
  { iata: 'PHX', icao: 'KPHX', name: 'Phoenix Sky Harbor International Airport', city: 'Phoenix', country: 'US', lat: 33.4353, lon: -112.0059, tier: 2 },
  { iata: 'PKX', icao: 'ZBAD', name: 'Beijing Daxing International Airport', city: 'Beijing', country: 'CN', lat: 39.5013, lon: 116.414, tier: 2 },
  { iata: 'PRG', icao: 'LKPR', name: 'Václav Havel Airport Prague', city: 'Prague', country: 'CZ', lat: 50.1009, lon: 14.2599, tier: 2 },
  { iata: 'PTY', icao: 'MPTO', name: 'Tocumen International Airport', city: 'Tocumen', country: 'PA', lat: 9.0714, lon: -79.3835, tier: 2 },
  { iata: 'PUS', icao: 'RKPK', name: 'Gimhae International Airport', city: 'Busan', country: 'KR', lat: 35.1795, lon: 128.938, tier: 1 },
  { iata: 'PVG', icao: 'ZSPD', name: 'Shanghai Pudong International Airport', city: 'Shanghai (Pudong)', country: 'CN', lat: 31.1434, lon: 121.805, tier: 1 },
  { iata: 'RGN', icao: 'VYYY', name: 'Yangon International Airport', city: 'Yangon', country: 'MM', lat: 16.9073, lon: 96.1332, tier: 2 },
  { iata: 'RUH', icao: 'OERK', name: 'King Khalid International Airport', city: 'Riyadh', country: 'SA', lat: 24.9576, lon: 46.6988, tier: 2 },
  { iata: 'SAN', icao: 'KSAN', name: 'San Diego International Airport', city: 'San Diego', country: 'US', lat: 32.7336, lon: -117.19, tier: 2 },
  { iata: 'SAW', icao: 'LTFJ', name: 'Istanbul Sabiha Gökçen International Airport', city: 'Pendik, Istanbul', country: 'TR', lat: 40.8986, lon: 29.3092, tier: 2 },
  { iata: 'SCL', icao: 'SCEL', name: 'Comodoro Arturo Merino Benítez International Airport', city: 'Santiago', country: 'CL', lat: -33.393, lon: -70.7858, tier: 1 },
  { iata: 'SEA', icao: 'KSEA', name: 'Seattle–Tacoma International Airport', city: 'Seattle', country: 'US', lat: 47.4479, lon: -122.3103, tier: 1 },
  { iata: 'SFO', icao: 'KSFO', name: 'San Francisco International Airport', city: 'San Francisco', country: 'US', lat: 37.6198, lon: -122.3748, tier: 1 },
  { iata: 'SGN', icao: 'VVTS', name: 'Tan Son Nhat International Airport', city: 'Ho Chi Minh City', country: 'VN', lat: 10.8188, lon: 106.652, tier: 2 },
  { iata: 'SHA', icao: 'ZSSS', name: 'Shanghai Hongqiao International Airport', city: 'Shanghai (Minhang)', country: 'CN', lat: 31.1981, lon: 121.3343, tier: 2 },
  { iata: 'SIN', icao: 'WSSS', name: 'Singapore Changi Airport', city: 'Singapore', country: 'SG', lat: 1.3502, lon: 103.994, tier: 1 },
  { iata: 'STN', icao: 'EGSS', name: 'London Stansted Airport', city: 'London, Essex', country: 'GB', lat: 51.885, lon: 0.235, tier: 2 },
  { iata: 'SVO', icao: 'UUEE', name: 'Sheremetyevo International Airport', city: 'Moscow', country: 'RU', lat: 55.9769, lon: 37.4112, tier: 2 },
  { iata: 'SYD', icao: 'YSSY', name: 'Sydney Kingsford Smith International Airport', city: 'Sydney (Mascot)', country: 'AU', lat: -33.9461, lon: 151.177, tier: 1 },
  { iata: 'SZX', icao: 'ZGSZ', name: 'Shenzhen Bao\'an International Airport', city: 'Shenzhen', country: 'CN', lat: 22.6395, lon: 113.8033, tier: 2 },
  { iata: 'TLV', icao: 'LLBG', name: 'Ben Gurion International Airport', city: 'Tel Aviv', country: 'IL', lat: 32.0114, lon: 34.8867, tier: 1 },
  { iata: 'TPE', icao: 'RCTP', name: 'Taiwan Taoyuan International Airport', city: 'Taoyuan', country: 'TW', lat: 25.0777, lon: 121.233, tier: 1 },
  { iata: 'TSA', icao: 'RCSS', name: 'Taipei Songshan International Airport', city: 'Taipei (Songshan)', country: 'TW', lat: 25.0672, lon: 121.5528, tier: 2 },
  { iata: 'VCE', icao: 'LIPZ', name: 'Venice Marco Polo Airport', city: 'Venezia (VE)', country: 'IT', lat: 45.5053, lon: 12.3519, tier: 2 },
  { iata: 'VIE', icao: 'LOWW', name: 'Vienna International Airport', city: 'Vienna', country: 'AT', lat: 48.1103, lon: 16.5697, tier: 1 },
  { iata: 'WAW', icao: 'EPWA', name: 'Warsaw Chopin Airport', city: 'Warsaw', country: 'PL', lat: 52.1657, lon: 20.9671, tier: 2 },
  { iata: 'XIY', icao: 'ZLXY', name: 'Xi\'an Xianyang International Airport', city: 'Xi\'an', country: 'CN', lat: 34.4422, lon: 108.7624, tier: 2 },
  { iata: 'YUL', icao: 'CYUL', name: 'Montreal / Pierre Elliott Trudeau International Airport', city: 'Montréal', country: 'CA', lat: 45.4678, lon: -73.7423, tier: 2 },
  { iata: 'YVR', icao: 'CYVR', name: 'Vancouver International Airport', city: 'Vancouver', country: 'CA', lat: 49.1939, lon: -123.184, tier: 1 },
  { iata: 'YYZ', icao: 'CYYZ', name: 'Toronto Pearson International Airport', city: 'Toronto', country: 'CA', lat: 43.6759, lon: -79.6294, tier: 1 },
  { iata: 'ZRH', icao: 'LSZH', name: 'Zürich Airport', city: 'Zurich', country: 'CH', lat: 47.4581, lon: 8.5481, tier: 1 },
];

export const FAMOUS_AIRPORTS = AIRPORTS.filter((a) => a.tier === 1);
